import Head from "next/head";
import Header from "@/components/layout/Header";
import Hero from "@/components/sections/Hero";
import News from "@/components/sections/News";
import Current from "@/components/sections/Current";
import GoTo from "@/components/sections/GoTo";
import Footer from "@/components/layout/Footer";

// import Footer from "@/components/layout/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>uva-nl/en</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mt-40 overflow-hidden">
        <Hero />
        <Current />
        <News />
        <GoTo />
      </main>
      <Footer />
    </>
  );
}
